// Generated by CoffeeScript 1.12.7
var CartModel,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CartModel = (function(superClass) {
  extend(CartModel, superClass);

  function CartModel() {
    return CartModel.__super__.constructor.apply(this, arguments);
  }

  return CartModel;

})(DreamPilot.Model);

//# sourceMappingURL=CartModel.js.map
