// Generated by CoffeeScript 1.10.0
var ModelApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ModelApp = (function(superClass) {
  extend(ModelApp, superClass);

  function ModelApp() {
    return ModelApp.__super__.constructor.apply(this, arguments);
  }

  ModelApp.prototype.init = function() {
    return this.initModels();
  };

  ModelApp.prototype.initModels = function() {
    this.user1 = new UserModel(this.e('ul[data-user1]').data('user1'));
    this.user2 = new UserModel(this.e('script[data-of="user2"]').html());
    this.user3 = new UserModel(this.user2);
    this.linkToScope('user1', 'user2', 'user3');
    console.log(this.getScope().get('user1.name'));
    this.user1.onChange('likes_drifting', function(field, value) {
      return console.log(field, '=', value);
    });
    return this;
  };

  return ModelApp;

})(DreamPilot.Application);

//# sourceMappingURL=ModelApp.js.map
