// Generated by CoffeeScript 1.10.0
var BasicApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

BasicApp = (function(superClass) {
  extend(BasicApp, superClass);

  function BasicApp($wrapper) {
    BasicApp.__super__.constructor.call(this, $wrapper);
    console.log('I am the basic app!');
    this.initVariables();
  }

  BasicApp.prototype.initVariables = function() {
    this.getScope().set({
      assignItOut: function() {
        var i, len, x, y;
        console.log('assignItOut called with args: ', arguments);
        x = 0;
        for (i = 0, len = arguments.length; i < len; i++) {
          y = arguments[i];
          x += y;
        }
        return x;
      },
      letItOut: function() {
        return alert('let it out!');
      }
    });
    setTimeout((function(_this) {
      return function() {
        return _this.getScope().set({
          lolo: 11,
          pepe: 8
        });
      };
    })(this), 2000);
    setTimeout((function(_this) {
      return function() {
        return _this.getScope().set({
          lolo: 5,
          pepe: 8
        });
      };
    })(this), 5000);
    setTimeout((function(_this) {
      return function() {
        return _this.getScope().set({
          lolo: 12,
          pepe: 8
        });
      };
    })(this), 7000);
    return this;
  };

  return BasicApp;

})(DreamPilot.Application);

//# sourceMappingURL=app.js.map
