// Generated by CoffeeScript 1.10.0
var BasicApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

BasicApp = (function(superClass) {
  extend(BasicApp, superClass);

  function BasicApp($element) {
    BasicApp.__super__.constructor.call(this, $element);
    console.log('I am the basic app!');
    this.initVariables();
  }

  BasicApp.prototype.initVariables = function() {
    this.getScope().set({
      lolo: 10,
      pepe: 7
    });
    setTimeout((function(_this) {
      return function() {
        return _this.getScope().set({
          lolo: 11,
          pepe: 8
        });
      };
    })(this), 2000);
    return this;
  };

  return BasicApp;

})(DreamPilot.Application);

//# sourceMappingURL=app.js.map
