// Generated by CoffeeScript 1.12.7
var RouterApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

RouterApp = (function(superClass) {
  extend(RouterApp, superClass);

  function RouterApp() {
    return RouterApp.__super__.constructor.apply(this, arguments);
  }

  RouterApp.prototype.Router = null;

  RouterApp.prototype.init = function() {
    return this.initRouter();
  };

  RouterApp.prototype.initRouter = function() {
    this.Router = new DreamPilot.Router(this).when('');
    return this;
  };

  return RouterApp;

})(DreamPilot.Application);

//# sourceMappingURL=RouterApp.js.map
