// Generated by CoffeeScript 1.12.7
var ChatModel,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ChatModel = (function(superClass) {
  extend(ChatModel, superClass);

  function ChatModel() {
    return ChatModel.__super__.constructor.apply(this, arguments);
  }

  ChatModel.prototype.getName = function() {
    return this.get('name');
  };

  ChatModel.prototype.getCreatedAt = function() {
    return this.get('created_at');
  };

  ChatModel.prototype.getContent = function() {
    return this.get('content');
  };

  ChatModel.prototype.setName = function(name) {
    return this.set('name', name);
  };

  ChatModel.prototype.setContent = function(content) {
    return this.set('content', content);
  };

  ChatModel.prototype.defineBasics = function() {
    ChatModel.__super__.defineBasics.call(this);
    this.idField = '_id';
    this.idIsInt = false;
    return this;
  };

  ChatModel.prototype.display = function() {
    var chatBox, cue;
    chatBox = $dp.e('ul.chat-box');
    cue = $dp.e('<li dp-click="chatClick(this, $event)" dp-class="{tiny: isTiny}">{0} ({1}): {2}</li>'.format(this.get('name'), this.get('created_at'), this.get('content')));
    chatBox.append(cue);
    this.getApp().embraceDomElement(cue);
    return this;
  };

  ChatModel.prototype.displayFiltered = function() {
    var chatBox, cue;
    chatBox = $dp.e('ul.chat-box-filtered');
    cue = $dp.e('<li dp-click="chatClick(this, $event)" dp-class="{tiny: isTiny}">{0} ({1}): {2}</li>'.format(this.get('name'), this.get('created_at'), this.get('content')));
    chatBox.append(cue);
    this.getApp().embraceDomElement(cue);
    return this;
  };

  ChatModel.prototype.displayEmbraced = function() {
    var chatBox, cue;
    chatBox = $dp.e('ul.chat-box-embraced');
    cue = $dp.e("<li dp-click=\"chatClick(this, $event)\">\n<span dp-value-read-from=\"col['" + (this.getId()) + "'].name\"></span> (<span dp-value-read-from=\"col['" + (this.getId()) + "'].created_at\"></span>):\n<span dp-value-read-from=\"col['" + (this.getId()) + "'].content\"></span>\n</li>");
    chatBox.append(cue);
    this.getApp().embraceDomElement(cue);
    return this;
  };

  return ChatModel;

})(DreamPilot.Model);

//# sourceMappingURL=ChatModel.js.map
