// Generated by CoffeeScript 1.12.7
var ChatModel,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ChatModel = (function(superClass) {
  extend(ChatModel, superClass);

  function ChatModel() {
    return ChatModel.__super__.constructor.apply(this, arguments);
  }

  ChatModel.prototype.getUserId = function() {
    return $dp.fn.int(this.get('user_id'));
  };

  ChatModel.prototype.getUser = function() {
    if (this.getApp().getUsersCol()) {
      return this.getApp().getUsersCol().get(this.getUserId());
    } else {
      return new UserModel;
    }
  };

  ChatModel.prototype.getName = function() {
    return this.getUser().getName() || '';
  };

  ChatModel.prototype.getCreatedAt = function() {
    return this.get('created_at');
  };

  ChatModel.prototype.getContent = function() {
    return this.get('content');
  };

  ChatModel.prototype.setContent = function(content) {
    return this.set('content', content);
  };

  ChatModel.prototype.getVisible = function() {
    return $dp.fn.bool(this.get('visible'));
  };

  ChatModel.prototype.linkUser = function() {
    this.set({
      user: this.getUser()
    });
    return this;
  };

  ChatModel.prototype.init = function() {
    return this;
  };

  ChatModel.prototype.defineBasics = function() {
    ChatModel.__super__.defineBasics.call(this);
    this.idField = '_id';
    this.idIsInt = false;
    return this;
  };

  ChatModel.prototype.display = function() {
    var chatBox, cue;
    chatBox = $dp.e('ul.chat-box');
    cue = $dp.e('<li dp-click="chatClick(this, $event)" dp-class="{tiny: isTiny}">{0} ({1}): {2}</li>'.format(this.getName(), this.getCreatedAt(), this.getContent()));
    chatBox.append(cue);
    this.getApp().embraceDomElement(cue);
    return this;
  };

  ChatModel.prototype.displayFiltered = function() {
    var chatBox, cue;
    chatBox = $dp.e('ul.chat-box-filtered');
    cue = $dp.e('<li dp-click="chatClick(this, $event)" dp-class="{tiny: isTiny}">{0} ({1}): {2}</li>'.format(this.getName(), this.getCreatedAt(), this.getContent()));
    chatBox.append(cue);
    this.getApp().embraceDomElement(cue);
    return this;
  };

  ChatModel.prototype.displayEmbraced = function() {
    var chatBox, cue;
    chatBox = $dp.e('ul.chat-box-embraced');
    cue = $dp.e("<li dp-click=\"chatClick(this, $event)\">\n<span dp-value-read-from=\"col['" + (this.getId()) + "'].user.name\"></span> (<span dp-value-read-from=\"col['" + (this.getId()) + "'].created_at\"></span>):\n<span dp-value-read-from=\"col['" + (this.getId()) + "'].content\"></span>\n<span>\n    <input type=\"checkbox\" dp-value-bind=\"col['" + (this.getId()) + "'].visible\" id=\"visible-" + (this.getId()) + "\">\n    <label for=\"visible-" + (this.getId()) + "\">Visible</label>\n</span>\n<span dp-show=\"col['" + (this.getId()) + "'].user.id\" dp-title=\"col['" + (this.getId()) + "'].user.id\">[user id test]</span>\n<span><button dp-click=\"col['" + (this.getId()) + "'].user.setRandomName()\">Set random name to user</button></span>\n</li>");
    chatBox.append(cue);
    this.getApp().embraceDomElement(cue);
    return this;
  };

  ChatModel.prototype.getFetchUrl = function() {
    return 'data.json';
  };

  return ChatModel;

})(DreamPilot.Model);

//# sourceMappingURL=ChatModel.js.map
