// Generated by CoffeeScript 1.12.7
var CollectionApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CollectionApp = (function(superClass) {
  extend(CollectionApp, superClass);

  function CollectionApp() {
    return CollectionApp.__super__.constructor.apply(this, arguments);
  }

  CollectionApp.prototype.init = function() {
    return this.loadChat();
  };

  CollectionApp.prototype.loadChat = function() {
    this.col = new ChatCollection().onLoad(function(col) {
      return col.map(function(model) {
        return model.display();
      });
    }).load();
    return this;
  };

  return CollectionApp;

})(DreamPilot.Application);

//# sourceMappingURL=CollectionApp.js.map
