// Generated by CoffeeScript 1.12.7
var UserCollection,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

UserCollection = (function(superClass) {
  extend(UserCollection, superClass);

  function UserCollection() {
    return UserCollection.__super__.constructor.apply(this, arguments);
  }

  UserCollection.prototype.defineBasics = function() {
    UserCollection.__super__.defineBasics.call(this);
    this.modelClassName = 'UserModel';
    return this;
  };

  return UserCollection;

})(DreamPilot.Collection);

//# sourceMappingURL=UserCollection.js.map
